version: '3.8' # Versión del formato del archivo Docker Compose

services:
  # ------------------------------------------
  # Servicio 1: NGINX (servidor web)
  # ------------------------------------------
  web:
    image: nginx:latest # Usa la imagen oficial de Nginx
    ports:
      - "8080:80" # Expone el puerto 80 del contenedor como 8080 en tu PC
    volumes:
      - ./web:/usr/share/nginx/html # Monta tu código fuente HTML/PHP en la carpeta de Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Monta tu archivo personalizado de configuración Nginx
    depends_on:
      - php # Espera a que el contenedor PHP esté listo

  # ------------------------------------------
  # Servicio 2: PHP-FPM (procesador PHP)
  # ------------------------------------------
  php:
    build: # En lugar de image, usamos build
      context: . # Usa la carpeta actual
      dockerfile: Dockerfile # Construye usando este archivo
    volumes:
      - ./web:/usr/share/nginx/html # Comparte los mismos archivos con Nginx
    depends_on:
      - db # Espera a que la base de datos esté lista antes de arrancar

  # ------------------------------------------
  # Servicio 3: MySQL (base de datos)
  # ------------------------------------------
  db:
    image: mysql:5.7 # Usa la imagen oficial de MySQL versión 5.7
    restart: always # Reinicia automáticamente si se cae
    environment:
      MYSQL_ROOT_PASSWORD: root # Contraseña del usuario root
      MYSQL_DATABASE: reloj_db # Nombre de la base que se va a crear automáticamente
      MYSQL_USER: user # Usuario adicional
      MYSQL_PASSWORD: password # Contraseña del usuario
    ports:
      - "3306:3306" # Expone MySQL al puerto 3306 (puedes conectarte con DBeaver o Workbench)
    volumes:
      - db_data:/var/lib/mysql # Guarda los datos en un volumen para que no se pierdan
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # Script SQL inicial

# ------------------------------------------
# Volúmenes para persistencia
# ------------------------------------------
volumes:
  db_data:
